public class Day35_SanjayGupta_List {
	// Case 1 : 1) Insert 2 Account records using List.
	
    /*public static void create2AccUsingList(){
        List<Account> accList1 = new List<Account>();
        Account acc1 = new Account(Name = '22 Oct 12 : 42 PM 1',Active__c = 'True', Rating = 'Hot');
        Account acc2 = new Account(Name = '22 Oct 12 : 42 PM 2',Active__c = 'False', Rating = 'Hot');
        accList1.add(acc1);
        accList1.add(acc2);
        insert accList1;
    }*/
    // Case 2: 2) Query 5 Account Records using SOQL and display the values through System.debug();
    /*public static void query5AccUsingSOQL(){
        List<Account> accList2 = [Select ID, NAME, RATING FROM ACCOUNT LIMIT 5];
        System.debug('Account query list:- '+accList2);
    }*/
}